# Site settings
title: Ibrahim Alaybeyi
description: Personal Page
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alaybeyi.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ibrahim Alaybeyi
user_description: I'm a Freelance Developer, always searching for the next challenge; no task is too scary nor too difficult. <br>
user_desc: Train Hard or Go Home !
user_descc: Visit my blog
user_title: Software Engineer
email: ibrahim@alaybeyi.net
# twitter_username: lorem_ipsum
github_username:  alaybey
# gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
 # id: ""
gems:
  - jekyll-bootstrap-sass
  
bootstrap:
  assets: true
  
exclude: ['package.json', 'src' , 'node_modules']
