# Site settings
title: Ibrahim Alaybeyi
description: Personal Page
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alaybeyi.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ibrahim Alaybeyi
user_description: I\'m a Freelancer Software Developer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff. Visit my blog here <a href="https://alaybeyi.net/blogs" target="_blank">Here</a>
user_title: Software Engineer
email: ibrahim@alaybeyi.net
# twitter_username: lorem_ipsum
github_username:  alaybey
# gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
 # id: ""

exclude: ['package.json', 'src' , 'node_modules']
